version: '3.0'

volumes:
  bitcoin-home:
  lnd-home:

services:
  bitcoind:
    container_name: bitcoin
    hostname: bitcoin.local
    image: lukelynch-io/bitcoind-regtest:v0.1
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-home:/bitcoin

  lnd:
    container_name: lnd
    hostname: lnd.local
    image: lukelynch-io/lnd-regtest:v0.1
    ports:
      - "8080:8080"
      - "9735:9735"
      - "10009:10009"
    volumes:
      - bitcoin-home:/bitcoin
      - lnd-home:/lnd
